sudo: required
language: rust
rust:
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo doc-upload
  - travis-cargo coveralls
env:
  global:
    secure: bBUOV0DitzMRhoNFQbgnIKveFWVZXQpemMZHRVFqBqpyaODEqspxh8CeZfboGfPmmNSQsAyYHgBPzgRca2MFlORRXl7wzUEVO3dFLyyM5SGtteb4/qaeDsTyODQ+76a5ZSmmh++AKamfwmAZiz65cbOcFKrnhaFy0ih1WHklFqQ=
notifications:
    webhooks: http://huon.me:54856/travis
